/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "ZipBooks.h"

/** ACTIVE_RECORD **/
ZipBooks::ZipBooks():wxSqliteActiveRecord(){
}

ZipBooks::ZipBooks(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

ZipBooks::ZipBooks(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool ZipBooks::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

ZipBooksRow* ZipBooks::RowFromResult(DatabaseResultSet* result){
	ZipBooksRow* row=new ZipBooksRow(this);

	row->GetFromResult(result);

	return row;
}

ZipBooksRow* ZipBooks::New(){
	ZipBooksRow* newRow=new ZipBooksRow(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool ZipBooks::Delete(wxString key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE book=?"),m_table.c_str()));
		pStatement->SetParamString(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}

ZipBooksRow* ZipBooks::Book(const wxString& key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE book=?"),m_table.c_str()));
		pStatement->SetParamString(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		if(!result->Next()) return NULL;
		ZipBooksRow* row=RowFromResult(result);
		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}

ZipBooksRow* ZipBooks::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		if(!result->Next()) return NULL;
		ZipBooksRow* row=RowFromResult(result);

		garbageRows.Add(row);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

ZipBooksRowSet* ZipBooks::WhereSet(const wxString& whereClause,const wxString& orderBy){
	ZipBooksRowSet* rowSet=new ZipBooksRowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}

		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return rowSet;

	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


ZipBooksRowSet* ZipBooks::All(const wxString& orderBy){
	ZipBooksRowSet* rowSet=new ZipBooksRowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);

		DatabaseResultSet* result= pStatement->ExecuteQuery();

		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return rowSet;

	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

ZipBooksRow::ZipBooksRow():wxActiveRecordRow(){
	newRow=true;
}

ZipBooksRow::ZipBooksRow(ZipBooks* activeRecord):wxActiveRecordRow(activeRecord){
	newRow=true;
}

ZipBooksRow::ZipBooksRow(const ZipBooksRow& src){
	if(&src==this)
		return;
	newRow=src.newRow;

	book=src.book;
	file=src.file;

}

ZipBooksRow::ZipBooksRow(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}


ZipBooksRow& ZipBooksRow::operator=(const ZipBooksRow& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;

	book=src.book;
	file=src.file;


	return *this;
}

bool ZipBooksRow::GetFromResult(DatabaseResultSet* result){

	newRow=false;
		book=result->GetResultString(wxT("book"));
	file=result->GetResultInt(wxT("file"));


	return true;
}


bool ZipBooksRow::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (book,file) VALUES (?,?)"),m_table.c_str()));
			pStatement->SetParamString(1,book);
			pStatement->SetParamInt(2,file);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);


			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET ,file=? WHERE book=?"),m_table.c_str()));
			pStatement->SetParamString(2,book);
			pStatement->SetParamInt(1,file);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}

		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool ZipBooksRow::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE book=?"),m_table.c_str()));
		pStatement->SetParamString(1,book);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



ZipFilesRow* ZipBooksRow::GetFile(){
	ZipFilesRow* owner= new ZipFilesRow(m_database,wxT("files"));
	PreparedStatement* pStatement=m_database->PrepareStatement(wxT("SELECT * FROM files WHERE file=?"));
	pStatement->SetParamInt(1,file);
	DatabaseResultSet* result= pStatement->ExecuteQuery();

	result->Next();
	owner->GetFromResult(result);
	garbageRows.Add(owner);
	m_database->CloseResultSet(result);
	m_database->CloseStatement(pStatement);
	return owner;
}



/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

ZipBooksRowSet::ZipBooksRowSet():wxActiveRecordRowSet(){
}

ZipBooksRowSet::ZipBooksRowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

ZipBooksRowSet::ZipBooksRowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

ZipBooksRow* ZipBooksRowSet::Item(unsigned long item){
	return (ZipBooksRow*)wxActiveRecordRowSet::Item(item);
}


bool ZipBooksRowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int ZipBooksRowSet::CMPFUNC_book(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	ZipBooksRow** m_item1=(ZipBooksRow**)item1;
	ZipBooksRow** m_item2=(ZipBooksRow**)item2;
	return (*m_item1)->book.Cmp((*m_item2)->book);
}

int ZipBooksRowSet::CMPFUNC_file(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	ZipBooksRow** m_item1=(ZipBooksRow**)item1;
	ZipBooksRow** m_item2=(ZipBooksRow**)item2;
	if((*m_item1)->file<(*m_item2)->file)
		return -1;
	else if((*m_item1)->file>(*m_item2)->file)
		return 1;
	else
		return 0;
}

CMPFUNC_proto ZipBooksRowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("book"))
		return (CMPFUNC_proto)CMPFUNC_book;
	else if(var==wxT("file"))
		return (CMPFUNC_proto)CMPFUNC_file;
	else
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations





////@@end custom implementations
