# =========================================================================
#     This makefile was generated by
#     Bakefile 0.2.8 (http://www.bakefile.org)
#     Do not modify, all changes will be overwritten!
# =========================================================================



# -------------------------------------------------------------------------
# These are configurable options:
# -------------------------------------------------------------------------

# 'install' program location 
INSTALL ?= install

# Destination root (/ is used if empty) 
DESTDIR ?= 

#  
AR ?= ar

#  
RANLIB ?= ranlib

# C compiler 
CC = gcc

# C++ compiler 
CXX = `$(WX_CONFIG) --cxx`

# Standard flags for CC 
CFLAGS ?= 

# Standard flags for C++ 
CXXFLAGS ?= 

# Standard preprocessor flags (common for CC and CXX) 
CPPFLAGS ?= 

# Standard linker flags 
LDFLAGS ?= 

# Location and arguments of wx-config script 
WX_CONFIG ?= wx-config

# Port of the wx library to build against [gtk1,gtk2,msw,x11,motif,mgl,mac,dfb]
WX_PORT ?= gtk2

# Use DLL build of wx library to use? [0,1]
WX_SHARED ?= 1

# Compile Unicode build of wxWidgets? [0,1]
WX_UNICODE ?= 1

# Use debug build of wxWidgets (define __WXDEBUG__)? [0,1]
WX_DEBUG ?= 0

# Version of the wx library to build against. 
WX_VERSION ?= 2.8



# -------------------------------------------------------------------------
# Do not modify the rest of this file!
# -------------------------------------------------------------------------

### Variables: ###

CPPDEPS = -MT$@ -MF`echo $@ | sed -e 's,\.o$$,.d,'` -MD -MP
WX_VERSION_MAJOR = $(shell echo $(WX_VERSION) | cut -c1,1)
WX_VERSION_MINOR = $(shell echo $(WX_VERSION) | cut -c2,2)
WX_CONFIG_FLAGS = $(WX_CONFIG_DEBUG_FLAG) $(WX_CONFIG_UNICODE_FLAG) \
	$(WX_CONFIG_SHARED_FLAG) --toolkit=$(WX_PORT) \
	--version=$(WX_VERSION_MAJOR).$(WX_VERSION_MINOR)
SQLITE3_STATIC_CFLAGS =  -DSQLITE_ENABLE_FTS3  $(CPPFLAGS) $(CFLAGS)
SQLITE3_STATIC_OBJECTS =  \
	build/sqlite3_static_sqlite3.o
WXSQLITE3_STATIC_CXXFLAGS = -DNDEBUG -IWxSQLite3 `$(WX_CONFIG) --cxxflags \
	$(WX_CONFIG_FLAGS)` $(CPPFLAGS) $(CXXFLAGS)
WXSQLITE3_STATIC_OBJECTS =  \
	build/wxsqlite3_static_wxsqlite3.o
BIN2C_CFLAGS =   $(CPPFLAGS) $(CFLAGS)
BIN2C_OBJECTS =  \
	build/bin2c_bin2c.o
MYRULIB_CFLAGS = -DNDEBUG -Ibuild -ISQLite3 -IWxSQLite3 -O2 `$(WX_CONFIG) --cflags \
	$(WX_CONFIG_FLAGS)` $(CPPFLAGS) $(CFLAGS)
MYRULIB_CXXFLAGS = -DNDEBUG -Ibuild -ISQLite3 -IWxSQLite3 -O2 `$(WX_CONFIG) \
	--cxxflags $(WX_CONFIG_FLAGS)` $(CPPFLAGS) $(CXXFLAGS)
MYRULIB_OBJECTS =  \
	build/myrulib_BaseThread.o \
	build/myrulib_ExpThread.o \
	build/myrulib_ExternalDlg.o \
	build/myrulib_FbAboutDlg.o \
	build/myrulib_FbAuthorDlg.o \
	build/myrulib_FbAuthorThread.o \
	build/myrulib_FbBookData.o \
	build/myrulib_FbBookEvent.o \
	build/myrulib_FbBookList.o \
	build/myrulib_FbBookMenu.o \
	build/myrulib_FbBookPanel.o \
	build/myrulib_FbBookThread.o \
	build/myrulib_FbCheckList.o \
	build/myrulib_FbColumnDlg.o \
	build/myrulib_FbConfigDlg.o \
	build/myrulib_FbConst.o \
	build/myrulib_FbDatabase.o \
	build/myrulib_FbDataOpenDlg.o \
	build/myrulib_FbDataPath.o \
	build/myrulib_FbEditBook.o \
	build/myrulib_FbExtractInfo.o \
	build/myrulib_FbDownloader.o \
	build/myrulib_FbFilterDlg.o \
	build/myrulib_FbFilterObj.o \
	build/myrulib_FbFrameAuthor.o \
	build/myrulib_FbFrameBase.o \
	build/myrulib_FbFrameDate.o \
	build/myrulib_FbFrameDownld.o \
	build/myrulib_FbFrameFolder.o \
	build/myrulib_FbFrameInfo.o \
	build/myrulib_FbFrameHtml.o \
	build/myrulib_FbFrameGenres.o \
	build/myrulib_FbFrameSearch.o \
	build/myrulib_FbFrameSequen.o \
	build/myrulib_FbGenres.o \
	build/myrulib_FbHtmlWindow.o \
	build/myrulib_FbImportThread.o \
	build/myrulib_FbLocale.o \
	build/myrulib_FbLogStream.o \
	build/myrulib_FbMainFrame.o \
	build/myrulib_FbMainMenu.o \
	build/myrulib_FbMasterData.o \
	build/myrulib_FbMasterList.o \
	build/myrulib_FbMenu.o \
	build/myrulib_FbNotebook.o \
	build/myrulib_FbParams.o \
	build/myrulib_FbReplaceDlg.o \
	build/myrulib_FbTreeListCtrl.o \
	build/myrulib_FbUpdateThread.o \
	build/myrulib_FbViewerDlg.o \
	build/myrulib_FbWindow.o \
	build/myrulib_ImpContext.o \
	build/myrulib_InfoCash.o \
	build/myrulib_InfoThread.o \
	build/myrulib_LimitedTextCtrl.o \
	build/myrulib_MyRuLibApp.o \
	build/myrulib_ParseCtx.o \
	build/myrulib_ProgressBar.o \
	build/myrulib_SettingsDlg.o \
	build/myrulib_TitleThread.o \
	build/myrulib_ZipReader.o \
	build/myrulib_md5.o \
	build/myrulib_base64.o \
	build/myrulib_treelistctrl.o
MYRULIB_ODEP =  build/ru.inc build/uk.inc build/be.inc

### Conditionally set variables: ###

ifeq ($(WX_DEBUG),0)
WX_CONFIG_DEBUG_FLAG = --debug=no
endif
ifeq ($(WX_DEBUG),1)
WX_CONFIG_DEBUG_FLAG = --debug=yes
endif
ifeq ($(WX_UNICODE),0)
WX_CONFIG_UNICODE_FLAG = --unicode=no
endif
ifeq ($(WX_UNICODE),1)
WX_CONFIG_UNICODE_FLAG = --unicode=yes
endif
ifeq ($(WX_SHARED),0)
WX_CONFIG_SHARED_FLAG = --static=yes
endif
ifeq ($(WX_SHARED),1)
WX_CONFIG_SHARED_FLAG = --static=no
endif


all: build
build:
	@mkdir -p build

### Targets: ###

all: test_for_selected_wxbuild build/libsqlite3_static.a build/libwxsqlite3_static.a build/bin2c build/myrulib

install: install_myrulib
	$(INSTALL) -d $(DESTDIR)/usr/share/locale/ru/LC_MESSAGES
	(cd build ; $(INSTALL) -m 644 -T ru.mo $(DESTDIR)/usr/share/locale/ru/LC_MESSAGES/myrulib.mo)
	$(INSTALL) -d $(DESTDIR)/usr/share/locale/uk/LC_MESSAGES
	(cd build ; $(INSTALL) -m 644 -T uk.mo $(DESTDIR)/usr/share/locale/uk/LC_MESSAGES/myrulib.mo)
	$(INSTALL) -d $(DESTDIR)/usr/share/locale/be/LC_MESSAGES
	(cd build ; $(INSTALL) -m 644 -T be.mo $(DESTDIR)/usr/share/locale/be/LC_MESSAGES/myrulib.mo)
	$(INSTALL) -d $(DESTDIR)/usr/share/icons/hicolor/48x48/apps
	(cd MyRuLib/desktop ; $(INSTALL) -m 644  myrulib.png $(DESTDIR)/usr/share/icons/hicolor/48x48/apps)
	$(INSTALL) -d $(DESTDIR)/usr/share/applications
	(cd MyRuLib/desktop ; $(INSTALL) -m 644  myrulib.desktop $(DESTDIR)/usr/share/applications)
	$(INSTALL) -d $(DESTDIR)/usr/share/pixmaps/
	ln -s ../icons/hicolor/48x48/apps/myrulib.png $(DESTDIR)/usr/share/pixmaps/myrulib.png

uninstall: uninstall_myrulib
	(cd $(DESTDIR)/usr/share/locale/ru/LC_MESSAGES ; rm -f myrulib.mo)
	(cd $(DESTDIR)/usr/share/locale/uk/LC_MESSAGES ; rm -f myrulib.mo)
	(cd $(DESTDIR)/usr/share/locale/be/LC_MESSAGES ; rm -f myrulib.mo)
	(cd $(DESTDIR)/usr/share/icons/hicolor/48x48/apps ; rm -f myrulib.png)
	(cd $(DESTDIR)/usr/share/applications ; rm -f myrulib.desktop)
	(cd $(DESTDIR)/usr/share/pixmaps ; rm -f myrulib.png)

clean: 
	rm -f build/*.o
	rm -f build/*.d
	rm -f build/libsqlite3_static.a
	rm -f build/libwxsqlite3_static.a
	rm -f build/bin2c
	rm -f build/ru.mo
	rm -f build/uk.mo
	rm -f build/be.mo
	rm -f build/ru.inc
	rm -f build/uk.inc
	rm -f build/be.inc
	rm -f build/myrulib

test_for_selected_wxbuild: 
	@$(WX_CONFIG) $(WX_CONFIG_FLAGS)

build/libsqlite3_static.a: $(SQLITE3_STATIC_OBJECTS)
	rm -f $@
	$(AR) rcu $@ $(SQLITE3_STATIC_OBJECTS)
	$(RANLIB) $@

build/libwxsqlite3_static.a: $(WXSQLITE3_STATIC_OBJECTS)
	rm -f $@
	$(AR) rcu $@ $(WXSQLITE3_STATIC_OBJECTS)
	$(RANLIB) $@

build/bin2c: $(BIN2C_OBJECTS)
	$(CC) -o $@ $(BIN2C_OBJECTS)  $(LDFLAGS)

build/ru.mo: build/bin2c MyRuLib/locale/ru.po
	msgfmt MyRuLib/locale/ru.po -o build/ru.mo

build/uk.mo: build/bin2c MyRuLib/locale/uk.po
	msgfmt MyRuLib/locale/uk.po -o build/uk.mo

build/be.mo: build/bin2c MyRuLib/locale/be.po
	msgfmt MyRuLib/locale/be.po -o build/be.mo

build/ru.inc: build/ru.mo
	build/bin2c build/ru.mo build/ru.inc file

build/uk.inc: build/uk.mo
	build/bin2c build/uk.mo build/uk.inc file

build/be.inc: build/be.mo
	build/bin2c build/be.mo build/be.inc file

build/myrulib: $(MYRULIB_OBJECTS) build/libwxsqlite3_static.a build/libsqlite3_static.a
	$(CXX) -o $@ $(MYRULIB_OBJECTS)     $(LDFLAGS)  build/libwxsqlite3_static.a build/libsqlite3_static.a -lexpat `$(WX_CONFIG) $(WX_CONFIG_FLAGS) --libs aui,html,core,net,base`
	strip build/myrulib

install_myrulib: build/myrulib
	$(INSTALL) -d $(DESTDIR)/usr/bin
	install -c build/myrulib $(DESTDIR)/usr/bin

uninstall_myrulib: 
	rm -f $(DESTDIR)/usr/bin/myrulib

build/sqlite3_static_sqlite3.o: ./SQLite3/sqlite3.c
	$(CC) -c -o $@ $(SQLITE3_STATIC_CFLAGS) $(CPPDEPS) $<

build/wxsqlite3_static_wxsqlite3.o: ./WxSQLite3/wxsqlite3.cpp
	$(CXX) -c -o $@ $(WXSQLITE3_STATIC_CXXFLAGS) $(CPPDEPS) $<

build/bin2c_bin2c.o: ./Bin2c/bin2c.c
	$(CC) -c -o $@ $(BIN2C_CFLAGS) $(CPPDEPS) $<

build/myrulib_BaseThread.o: ./MyRuLib/BaseThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_ExpThread.o: ./MyRuLib/ExpThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_ExternalDlg.o: ./MyRuLib/ExternalDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbAboutDlg.o: ./MyRuLib/FbAboutDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbAuthorDlg.o: ./MyRuLib/FbAuthorDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbAuthorThread.o: ./MyRuLib/FbAuthorThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbBookData.o: ./MyRuLib/FbBookData.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbBookEvent.o: ./MyRuLib/FbBookEvent.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbBookList.o: ./MyRuLib/FbBookList.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbBookMenu.o: ./MyRuLib/FbBookMenu.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbBookPanel.o: ./MyRuLib/FbBookPanel.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbBookThread.o: ./MyRuLib/FbBookThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbCheckList.o: ./MyRuLib/FbCheckList.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbColumnDlg.o: ./MyRuLib/FbColumnDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbConfigDlg.o: ./MyRuLib/FbConfigDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbConst.o: ./MyRuLib/FbConst.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbDatabase.o: ./MyRuLib/FbDatabase.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbDataOpenDlg.o: ./MyRuLib/FbDataOpenDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbDataPath.o: ./MyRuLib/FbDataPath.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbEditBook.o: ./MyRuLib/FbEditBook.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbExtractInfo.o: ./MyRuLib/FbExtractInfo.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbDownloader.o: ./MyRuLib/FbDownloader.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFilterDlg.o: ./MyRuLib/FbFilterDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFilterObj.o: ./MyRuLib/FbFilterObj.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameAuthor.o: ./MyRuLib/FbFrameAuthor.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameBase.o: ./MyRuLib/FbFrameBase.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameDate.o: ./MyRuLib/FbFrameDate.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameDownld.o: ./MyRuLib/FbFrameDownld.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameFolder.o: ./MyRuLib/FbFrameFolder.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameInfo.o: ./MyRuLib/FbFrameInfo.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameHtml.o: ./MyRuLib/FbFrameHtml.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameGenres.o: ./MyRuLib/FbFrameGenres.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameSearch.o: ./MyRuLib/FbFrameSearch.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbFrameSequen.o: ./MyRuLib/FbFrameSequen.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbGenres.o: ./MyRuLib/FbGenres.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbHtmlWindow.o: ./MyRuLib/FbHtmlWindow.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbImportThread.o: ./MyRuLib/FbImportThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbLocale.o: ./MyRuLib/FbLocale.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbLogStream.o: ./MyRuLib/FbLogStream.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbMainFrame.o: ./MyRuLib/FbMainFrame.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbMainMenu.o: ./MyRuLib/FbMainMenu.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbMasterData.o: ./MyRuLib/FbMasterData.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbMasterList.o: ./MyRuLib/FbMasterList.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbMenu.o: ./MyRuLib/FbMenu.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbNotebook.o: ./MyRuLib/FbNotebook.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbParams.o: ./MyRuLib/FbParams.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbReplaceDlg.o: ./MyRuLib/FbReplaceDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbTreeListCtrl.o: ./MyRuLib/FbTreeListCtrl.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbUpdateThread.o: ./MyRuLib/FbUpdateThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbViewerDlg.o: ./MyRuLib/FbViewerDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_FbWindow.o: ./MyRuLib/FbWindow.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_ImpContext.o: ./MyRuLib/ImpContext.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_InfoCash.o: ./MyRuLib/InfoCash.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_InfoThread.o: ./MyRuLib/InfoThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_LimitedTextCtrl.o: ./MyRuLib/LimitedTextCtrl.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_MyRuLibApp.o: ./MyRuLib/MyRuLibApp.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_ParseCtx.o: ./MyRuLib/ParseCtx.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_ProgressBar.o: ./MyRuLib/ProgressBar.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_SettingsDlg.o: ./MyRuLib/SettingsDlg.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_TitleThread.o: ./MyRuLib/TitleThread.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_ZipReader.o: ./MyRuLib/ZipReader.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_md5.o: ./MyRuLib/md5.c $(MYRULIB_ODEP)
	$(CC) -c -o $@ $(MYRULIB_CFLAGS) $(CPPDEPS) $<

build/myrulib_base64.o: ./MyRuLib/wx/base64.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

build/myrulib_treelistctrl.o: ./MyRuLib/wx/treelistctrl.cpp $(MYRULIB_ODEP)
	$(CXX) -c -o $@ $(MYRULIB_CXXFLAGS) $(CPPDEPS) $<

.PHONY: all install uninstall clean install_myrulib uninstall_myrulib


# Dependencies tracking:
-include build/*.d
