Document: myrulib
Title: Debian myrulib Manual
Author: <insert document author here>
Abstract: This manual describes what myrulib is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/myrulib/myrulib.sgml.gz

Format: postscript
Files: /usr/share/doc/myrulib/myrulib.ps.gz

Format: text
Files: /usr/share/doc/myrulib/myrulib.text.gz

Format: HTML
Index: /usr/share/doc/myrulib/html/index.html
Files: /usr/share/doc/myrulib/html/*.html
