/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////


#ifndef __PARAMS_
#define __PARAMS_

////@@begin gen include
#include "wxActiveRecord.h"
#include <wx/wx.h>
#include <wx/string.h>
#include <wx/datetime.h>

////@@end gen include

////@@begin custom include
////@@end custom include

////@@begin gen forward
class Params;
class ParamsRow;
class ParamsRowSet;


////@@end gen forward

////@@begin custom forward
////@@end custom forward

////@@begin gen arClass
class Params: public wxSqliteActiveRecord{
protected:
	ParamsRow* RowFromResult(DatabaseResultSet* result);
public:
	Params();
	Params(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("params"));
	Params(DatabaseLayer* database,const wxString& table=wxT("params"));
	bool Create(const wxString& name,const wxString& server=wxEmptyString,const wxString& user=wxEmptyString,const wxString& password=wxEmptyString,const wxString& table=wxT("params"));
	
	ParamsRow* New();
	bool Delete(int key);

	
	ParamsRow* Id(int key);

	ParamsRow* Where(const wxString& whereClause);
	ParamsRowSet* WhereSet(const wxString& whereClause,const wxString& orderBy=wxEmptyString);
	ParamsRowSet* All(const wxString& orderBy=wxEmptyString); 

////@@begin custom arClass
public:





////@@end custom arClass
};
////@@end gen arClass

////@@begin gen arRow
class ParamsRow: public wxActiveRecordRow{
public:
	ParamsRow();
	ParamsRow(const ParamsRow& src);
	ParamsRow(Params* activeRecord);
	ParamsRow(DatabaseLayer* database,const wxString& table=wxT("params"));
	ParamsRow& operator=(const ParamsRow& src);
	bool GetFromResult(DatabaseResultSet* result);
public:
	int value;
	int id;
	wxString text;

public:
	
	
	bool Save();
	bool Delete();
	
	
////@@begin custom arRow
public:





////@@end custom arRow	

};
////@@end gen arRow

////@@begin gen arSet
class ParamsRowSet: public wxActiveRecordRowSet{
public:
	ParamsRowSet();
	ParamsRowSet(wxActiveRecord* activeRecord);
	ParamsRowSet(DatabaseLayer* database,const wxString& table=wxT("params"));
	virtual ParamsRow* Item(unsigned long item);
	
	virtual bool SaveAll();
	
	
protected:
	static int CMPFUNC_value(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_id(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_text(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	static int CMPFUNC_global(wxActiveRecordRow** item1,wxActiveRecordRow** item2);
	virtual CMPFUNC_proto GetCmpFunc(const wxString& var) const;

////@@begin custom arSet
public:





////@@end custom arSet
};
////@@end gen arSet

#endif /* __PARAMS_ */