/////////////////////////////////////////////////////
// Generated By wxActiveRecordGenerator v 1.2.0-rc3
/////////////////////////////////////////////////////

#include "Params.h"

/** ACTIVE_RECORD **/
Params::Params():wxSqliteActiveRecord(){
}

Params::Params(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table):wxSqliteActiveRecord(name,server,user,password,table){
}

Params::Params(DatabaseLayer* database,const wxString& table):wxSqliteActiveRecord(database,table){
}

bool Params::Create(const wxString& name,const wxString& server,const wxString& user,const wxString& password,const wxString& table){
	return wxSqliteActiveRecord::Create(name,server,user,password,table);
}

ParamsRow* Params::RowFromResult(DatabaseResultSet* result){
	ParamsRow* row=new ParamsRow(this);

	row->GetFromResult(result);

	return row;
}

ParamsRow* Params::New(){
	ParamsRow* newRow=new ParamsRow(this);
	garbageRows.Add(newRow);
	return newRow;
}
bool Params::Delete(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE id=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}



ParamsRow* Params::Id(int key){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("SELECT * FROM %s WHERE id=?"),m_table.c_str()));
		pStatement->SetParamInt(1,key);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		ParamsRow* row = NULL;
		if (result->Next()) {
			row = RowFromResult(result);
			garbageRows.Add(row);
		} else {
			row = New();
			row->id = key;
			row->value = 1;
		}
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return NULL;
	}
}

ParamsRow* Params::Where(const wxString& whereClause){
	try{
		wxString prepStatement = wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		ParamsRow* row = NULL;
		if (result->Next()) {
			ParamsRow* row=RowFromResult(result);
			garbageRows.Add(row);
		}
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return row;
	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

ParamsRowSet* Params::WhereSet(const wxString& whereClause,const wxString& orderBy){
	ParamsRowSet* rowSet=new ParamsRowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s WHERE %s"),m_table.c_str(),whereClause.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);
		DatabaseResultSet* result= pStatement->ExecuteQuery();

		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}

		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return rowSet;

	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}


ParamsRowSet* Params::All(const wxString& orderBy){
	ParamsRowSet* rowSet=new ParamsRowSet();
	try{
		wxString prepStatement=wxString::Format(wxT("SELECT * FROM %s"),m_table.c_str());
		if(!orderBy.IsEmpty())
			prepStatement+=wxT(" ORDER BY ")+orderBy;
		PreparedStatement* pStatement=m_database->PrepareStatement(prepStatement);

		DatabaseResultSet* result= pStatement->ExecuteQuery();

		if(result){
			while(result->Next()){
				rowSet->Add(RowFromResult(result));
			}
		}
		garbageRowSets.Add(rowSet);
		m_database->CloseResultSet(result);
		m_database->CloseStatement(pStatement);
		return rowSet;

	}
	catch (DatabaseLayerException& e)
	{
		ProcessException(e);
		return 0;
	}
}

/** END ACTIVE RECORD **/

/** ACTIVE RECORD ROW **/

ParamsRow::ParamsRow():wxActiveRecordRow(){
	newRow=true;
}

ParamsRow::ParamsRow(Params* activeRecord):wxActiveRecordRow(activeRecord){
	newRow=true;
}

ParamsRow::ParamsRow(const ParamsRow& src){
	if(&src==this)
		return;
	newRow=src.newRow;

	value=src.value;
	id=src.id;
	text=src.text;

}

ParamsRow::ParamsRow(DatabaseLayer* database,const wxString& table):wxActiveRecordRow(database,table){
	newRow=true;
}


ParamsRow& ParamsRow::operator=(const ParamsRow& src){
	if(&src==this)
		return *this;
	newRow=src.newRow;

	value=src.value;
	id=src.id;
	text=src.text;


	return *this;
}

bool ParamsRow::GetFromResult(DatabaseResultSet* result){

	newRow=false;
		value=result->GetResultInt(wxT("value"));
	id=result->GetResultInt(wxT("id"));
	text=result->GetResultString(wxT("text"));


	return true;
}


bool ParamsRow::Save(){
	try{
		if(newRow){
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("INSERT INTO %s (value,text) VALUES (?,?)"),m_table.c_str()));
			pStatement->SetParamInt(1,value);
			pStatement->SetParamString(2,text);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);


			newRow=false;
		}
		else{
			PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("UPDATE %s SET value=?,text=? WHERE id=?"),m_table.c_str()));
			pStatement->SetParamInt(1,value);
			pStatement->SetParamInt(3,id);
			pStatement->SetParamString(2,text);
			pStatement->RunQuery();
			m_database->CloseStatement(pStatement);

		}

		return true;
	}
	catch (DatabaseLayerException& e)
	{
		wxActiveRecord::ProcessException(e);
		return false;
	}
}

bool ParamsRow::Delete(){
	try{
		PreparedStatement* pStatement=m_database->PrepareStatement(wxString::Format(wxT("DELETE FROM %s WHERE id=?"),m_table.c_str()));
		pStatement->SetParamInt(1,id);
		pStatement->ExecuteUpdate();
		return true;
	}
	catch(DatabaseLayerException& e){
		throw(e);
		return false;
	}
}





/** END ACTIVE RECORD ROW **/

/** ACTIVE RECORD ROW SET **/

ParamsRowSet::ParamsRowSet():wxActiveRecordRowSet(){
}

ParamsRowSet::ParamsRowSet(wxActiveRecord* activeRecord):wxActiveRecordRowSet(activeRecord){
}

ParamsRowSet::ParamsRowSet(DatabaseLayer* database,const wxString& table):wxActiveRecordRowSet(database,table){
}

ParamsRow* ParamsRowSet::Item(unsigned long item){
	return (ParamsRow*)wxActiveRecordRowSet::Item(item);
}


bool ParamsRowSet::SaveAll(){
	try{
		m_database->BeginTransaction();
		for(unsigned long i=0;i<Count();i++)
			Item(i)->Save();
		m_database->Commit();
		return true;
	}
	catch (DatabaseLayerException& e)
	{
		m_database->RollBack();
		wxActiveRecord::ProcessException(e);
		return false;
	}
}


int ParamsRowSet::CMPFUNC_value(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	ParamsRow** m_item1=(ParamsRow**)item1;
	ParamsRow** m_item2=(ParamsRow**)item2;
	if((*m_item1)->value<(*m_item2)->value)
		return -1;
	else if((*m_item1)->value>(*m_item2)->value)
		return 1;
	else
		return 0;
}

int ParamsRowSet::CMPFUNC_id(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	ParamsRow** m_item1=(ParamsRow**)item1;
	ParamsRow** m_item2=(ParamsRow**)item2;
	if((*m_item1)->id<(*m_item2)->id)
		return -1;
	else if((*m_item1)->id>(*m_item2)->id)
		return 1;
	else
		return 0;
}

int ParamsRowSet::CMPFUNC_text(wxActiveRecordRow** item1,wxActiveRecordRow** item2){
	ParamsRow** m_item1=(ParamsRow**)item1;
	ParamsRow** m_item2=(ParamsRow**)item2;
	return (*m_item1)->text.Cmp((*m_item2)->text);
}

CMPFUNC_proto ParamsRowSet::GetCmpFunc(const wxString& var) const{
	if(var==wxT("value"))
		return (CMPFUNC_proto)CMPFUNC_value;
	else if(var==wxT("id"))
		return (CMPFUNC_proto)CMPFUNC_id;
	else if(var==wxT("text"))
		return (CMPFUNC_proto)CMPFUNC_text;
	else
	return (CMPFUNC_proto)CMPFUNC_default;
}



/** END ACTIVE RECORD ROW SET **/

////@@begin custom implementations






////@@end custom implementations
